### ISSUE TITLE
Import Fieldpack Dropdown Option groups

### ISSUE THREAD

**Issue by robsonsobral** [EllisLab/PlayaMatrixImporter#12]
Hi!

The old Fieldpack Dropdown allowed us to use option groups. Something like:

```
 : --
volume
    cup : xícara(s) de chá
    teaspoon : colher(es) de chá
    coffeespoon : colher(es) de café
    tablespoon : colher(es) de sopa
    desertspoon : colher(es) de sobremesa
    glass : copo(s) americano(s)
    scoop(s)
    ml
    l
mass
    g
    kg
pinch : pitada
containers
    can : lata(s)
    package : pacote(s)
    jar : pote(s)
    glass : vidro(s)
length
    cm
```

In this case, the imported values for groups came as an empty string.

Thank you for your attention.

**Comment by kevincupp** [comment]
Sorry for the delay, Robson! I was out last week.

Ah yes sorry about that. Since EE2's fieldtypes doesn't support groups, we'd have to collapse everything to one level. Is that ok?

**Comment by robsonsobral** [comment]
> Sorry for the delay, Robson! I was out last week.

No problem, Kevin!

> Since EE2's fieldtypes doesn't support groups, we'd have to collapse everything to one level. Is that ok?

Of course. I already did that manually and imported everything again. I reported to help other devs.

Thank you, @kevincupp !
