### ISSUE TITLE
Timeout errors

### ISSUE THREAD

**Issue by JonaGreen** [EllisLab/PlayaMatrixImporter#14]
I keep getting timeout errors.  Is there something I'm missing? 
We use MSM with multiple sites set up.  Our largest site was tested on development server and timed out so tested a tiny site in comparison but still timed out (I appreciate still same database).

**Comment by kevincupp** [comment]
Is it a PHP timeout? Can you increase your PHP timeout limit?

**Comment by JonaGreen** [comment]
Just increased PHP timeout and still getting 524 timeout error.

**Comment by kevincupp** [comment]
Are you behind a caching proxy such as CloudFlare? You'll need either to adjust the timeout settings for the proxy or access your server directly.

**Comment by JonaGreen** [comment]
Yes we are, I’ll inform IT and inform you of the outcome. Thanks.



Cheers

Jon

*Jonathan Green*
*Web Developer*
*BSc (Hons) MMT*

*Pico Technology*
James House, Colmworth Business Park,
St Neots, Cambridgeshire, PE19 8YP.

Email: jonathan.green@picotech.com

Tel:+44 (0) 1480 396 395 <+441480396395>
Fax:+44 (0) 1480 396 296 <+441480396296>

[image: http://www.picotech.com/images/signature.png]
<http://www.picotech.com/>





*From:* Kevin Cupp [mailto:notifications@github.com]
*Sent:* 29 August 2017 17:43
*To:* EllisLab/PlayaMatrixImporter
*Cc:* Jonathan Green; Author
*Subject:* Re: [EllisLab/PlayaMatrixImporter] Timeout errors (#14)



Are you behind a caching proxy such as CloudFlare? You'll need either to
adjust the timeout settings for the proxy or access your server directly.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/EllisLab/PlayaMatrixImporter/issues/14#issuecomment-325723148>,
or mute the thread

**Comment by JonaGreen** [comment]
OK, so we're still having issues.  Timeouts have ceased but database errors (see attached) stop the process in its tracks. I noticed that the plugin runs across the entire database which consists of 7 websites where Matrix and Playa have been used extensively.  Is there an issue with MSM with multiple sites?
![dberror](https://user-images.githubusercontent.com/17765898/29878434-6c7830de-8d9a-11e7-8ae2-e041d4cfc7e5.png)

**Comment by kevincupp** [comment]
We haven't seen any issues with MSM. If there is a lot of data in these fields, this also may be a result of conservative server settings. Could you check the value of your `max_allowed_packet` setting in MySQL? If it's fairly low, could you try increasing it to say 128M or so just to perform the import?

**Comment by JonaGreen** [comment]
the figure for max_allowed_packet is 134217728

**Comment by kevincupp** [comment]
Ok that seems pretty high already. Do you know about how much data you have in your `exp_matrix_data`? How many rows and columns?

Here is some more information from MySQL about this particular error:

https://dev.mysql.com/doc/refman/5.7/en/error-lost-connection.html

**Comment by JonaGreen** [comment]
I've been informed by IT that the issue may be down to the amount of columns we have.  Rows seem reasonable but I'll let you be the judge of that info below. 

How can I reduce the column count of redundant columns 


# Number of rows
mysql> select count(*) from exp_matrix_data;
+----------+
| count(*) |
+----------+
|    12869 |
+----------+



# Approx number of columns around 400
root@weblive:/data# echo "show create table eengine.exp_matrix_data\G" | mysql | wc -l
449




*************************** 1. row ***************************
       Table: exp_matrix_data
Create Table: CREATE TABLE `exp_matrix_data` (
  `row_id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `site_id` int(4) unsigned DEFAULT '1',
  `entry_id` int(10) unsigned DEFAULT NULL,
  `field_id` int(6) unsigned DEFAULT NULL,
  `var_id` int(6) unsigned DEFAULT NULL,
  `is_draft` tinyint(1) unsigned DEFAULT '0',
  `row_order` int(4) unsigned DEFAULT NULL,
  `col_id_1` text,
  `col_id_2` text,
  `col_id_3` text,
  `col_id_4` text,
  `col_id_5` text,
  `col_id_6` text,
  `col_id_7` text,
  `col_id_8` text,
  `col_id_9` text,
  `col_id_10` text,
  `col_id_12` text,
  `col_id_13` text,
  `col_id_14` text,
  `col_id_15` text,
  `col_id_16` text,
  `col_id_18` text,
  `col_id_21` text,
  `col_id_27` text,
  `col_id_28` text,
  `col_id_29` text,
  `col_id_30` text,
  `col_id_31` text,
  `col_id_32` text,
  `col_id_33` text,
  `col_id_34` text,
  `col_id_35` text,
  `col_id_36` text,
  `col_id_37` text,
  `col_id_38` text,
  `col_id_39` text,
  `col_id_40` text,
  `col_id_41` text,
  `col_id_42` text,
  `col_id_43` text,
  `col_id_44` text,
  `col_id_45` text,
  `col_id_46` text,
  `col_id_48` text,
  `col_id_54` text,
  `col_id_55` text,
  `col_id_58` text,
  `col_id_59` text,
  `col_id_60` text,
  `col_id_61` text,
  `col_id_62` text,
  `col_id_63` text,
  `col_id_64` text,
  `col_id_65` text,
  `col_id_66` text,
  `col_id_67` text,
  `col_id_69` text,
  `col_id_70` text,
  `col_id_71` text,
  `col_id_72` text,
  `col_id_74` text,
  `col_id_75` text,
  `col_id_76` text,
  `col_id_89` text,
  `col_id_90` text,
  `col_id_97` text,
  `col_id_98` text,
  `col_id_99` text,
  `col_id_100` text,
  `col_id_101` text,
  `col_id_102` text,
  `col_id_105` text,
  `col_id_106` text,
  `col_id_107` text,
  `col_id_112` text,
  `col_id_116` text,
  `col_id_117` text,
  `col_id_118` text,
  `col_id_120` text,
  `col_id_121` text,
  `col_id_122` text,
  `col_id_124` text,
  `col_id_125` text,
  `col_id_127` text,
  `col_id_128` text,
  `col_id_129` text,
  `col_id_130` text,
  `col_id_131` text,
  `col_id_132` text,
  `col_id_133` text,
  `col_id_134` text,
  `col_id_135` text,
  `col_id_136` text,
  `col_id_137` text,
  `col_id_138` text,
  `col_id_139` text,
  `col_id_140` text,
  `col_id_141` text,
  `col_id_142` text,
  `col_id_143` text,
  `col_id_144` text,
  `col_id_145` text,
  `col_id_146` text,
  `col_id_147` text,
  `col_id_148` text,
  `col_id_149` text,
  `col_id_150` text,
  `col_id_151` text,
  `col_id_152` text,
  `col_id_161` text,
  `col_id_171` text,
  `col_id_191` text,
  `col_id_241` text,
  `col_id_251` text,
  `col_id_261` text,
  `col_id_271` text,
  `col_id_281` text,
  `col_id_301` text,
  `col_id_311` text,
  `col_id_321` text,
  `col_id_331` text,
  `col_id_341` text,
  `col_id_351` text,
  `col_id_361` text,
  `col_id_371` text,
  `col_id_381` text,
  `col_id_521` text,
  `col_id_531` text,
  `col_id_611` text,
  `col_id_621` text,
  `col_id_631` text,
  `col_id_641` text,
  `col_id_651` text,
  `col_id_661` text,
  `col_id_671` text,
  `col_id_681` text,
  `col_id_691` text,
  `col_id_701` text,
  `col_id_751` text,
  `col_id_761` text,
  `col_id_771` text,
  `col_id_781` text,
  `col_id_791` text,
  `col_id_801` text,
  `col_id_811` text,
  `col_id_821` text,
  `col_id_841` text,
  `col_id_851` text,
  `col_id_861` text,
  `col_id_871` text,
  `col_id_881` text,
  `col_id_891` text,
  `col_id_901` text,
  `col_id_911` text,
  `col_id_921` text,
  `col_id_931` text,
  `col_id_941` text,
  `col_id_951` text,
  `col_id_961` text,
  `col_id_971` text,
  `col_id_981` text,
  `col_id_991` text,
  `col_id_1001` text,
  `col_id_1011` text,
  `col_id_1021` text,
  `col_id_1041` text,
  `col_id_1051` text,
  `col_id_1061` text,
  `col_id_1071` text,
  `col_id_1081` text,
  `col_id_1091` text,
  `col_id_1101` text,
  `col_id_1111` text,
  `col_id_1121` text,
  `col_id_1131` text,
  `col_id_1141` text,
  `col_id_1151` text,
  `col_id_1161` text,
  `col_id_1171` text,
  `col_id_1181` text,
  `col_id_1191` text,
  `col_id_1201` text,
  `col_id_1211` text,
  `col_id_1221` text,
  `col_id_1231` text,
  `col_id_1241` text,
  `col_id_1251` text,
  `col_id_1261` text,
  `col_id_1271` text,
  `col_id_1291` text,
  `col_id_1301` text,
  `col_id_1311` text,
  `col_id_1321` text,
  `col_id_1331` text,
  `col_id_1341` text,
  `col_id_1351` text,
  `col_id_1361` text,
  `col_id_1371` text,
  `col_id_1381` text,
  `col_id_1391` text,
  `col_id_1401` text,
  `col_id_1411` text,
  `col_id_1431` text,
  `col_id_1441` text,
  `col_id_1451` text,
  `col_id_1471` text,
  `col_id_1481` text,
  `col_id_1491` text,
  `col_id_1501` text,
  `col_id_1511` text,
  `col_id_1521` text,
  `col_id_1531` text,
  `col_id_1541` text,
  `col_id_1571` text,
  `col_id_1581` text,
  `col_id_1591` text,
  `col_id_1601` text,
  `col_id_1611` text,
  `col_id_1621` text,
  `col_id_1631` text,
  `col_id_1641` text,
  `col_id_1651` text,
  `col_id_1661` text,
  `col_id_1671` text,
  `col_id_1681` text,
  `col_id_1691` text,
  `col_id_1701` text,
  `col_id_1711` text,
  `col_id_1721` text,
  `col_id_1731` text,
  `col_id_1741` text,
  `col_id_1751` text,
  `col_id_1761` text,
  `col_id_1771` text,
  `col_id_1781` text,
  `col_id_1791` text,
  `col_id_1801` text,
  `col_id_1811` text,
  `col_id_1821` text,
  `col_id_1831` text,
  `col_id_1841` text,
  `col_id_1851` text,
  `col_id_1861` text,
  `col_id_1871` text,
  `col_id_1881` text,
  `col_id_1891` text,
  `col_id_1901` text,
  `col_id_1911` text,
  `col_id_1921` text,
  `col_id_1931` text,
  `col_id_1941` text,
  `col_id_1951` text,
  `col_id_1961` text,
  `col_id_1971` text,
  `col_id_1981` text,
  `col_id_1991` text,
  `col_id_2001` text,
  `col_id_2011` text,
  `col_id_2021` text,
  `col_id_2031` text,
  `col_id_2041` text,
  `col_id_2051` text,
  `col_id_2061` text,
  `col_id_2071` text,
  `col_id_2081` text,
  `col_id_2091` text,
  `col_id_2111` text,
  `col_id_2121` text,
  `col_id_2131` text,
  `col_id_2141` text,
  `col_id_2151` text,
  `col_id_2161` text,
  `col_id_2171` text,
  `col_id_2181` text,
  `col_id_2191` text,
  `col_id_2201` text,
  `col_id_2211` text,
  `col_id_2221` text,
  `col_id_2231` text,
  `col_id_2241` text,
  `col_id_2251` text,
  `col_id_2261` text,
  `col_id_2271` text,
  `col_id_2281` text,
  `col_id_2291` text,
  `col_id_2301` text,
  `col_id_2311` text,
  `col_id_2341` text,
  `col_id_2351` text,
  `col_id_2361` text,
  `col_id_2371` text,
  `col_id_2381` text,
  `col_id_2391` text,
  `col_id_2401` text,
  `col_id_2411` text,
  `col_id_2431` text,
  `col_id_2441` text,
  `col_id_2451` text,
  `col_id_2461` text,
  `col_id_2471` text,
  `col_id_2481` text,
  `col_id_2491` varchar(75) DEFAULT NULL,
  `col_id_2501` text,
  `col_id_2511` text,
  `col_id_2521` text,
  `col_id_2531` text,
  `col_id_2541` text,
  `col_id_2551` text,
  `col_id_2561` text,
  `col_id_2571` text,
  `col_id_2581` text,
  `col_id_2591` text,
  `col_id_2601` text,
  `col_id_2611` text,
  `col_id_2621` text,
  `col_id_2631` text,
  `col_id_2641` text,
  `col_id_2651` text,
  `col_id_2661` text,
  `col_id_2671` text,
  `col_id_2681` text,
  `col_id_2691` text,
  `col_id_2701` text,
  `col_id_2711` text,
  `col_id_2721` text,
  `col_id_2731` text,
  `col_id_2741` text,
  `col_id_2751` text,
  `col_id_2761` text,
  `col_id_2771` text,
  `col_id_2781` text,
  `col_id_2791` text,
  `col_id_2801` text,
  `col_id_2811` text,
  `col_id_2821` text,
  `col_id_2831` text,
  `col_id_2841` text,
  `col_id_2851` text,
  `col_id_2861` text,
  `col_id_2871` text,
  `col_id_2881` text,
  `col_id_2891` text,
  `col_id_2901` text,
  `col_id_2911` text,
  `col_id_2921` text,
  `col_id_2931` text,
  `col_id_2941` text,
  `col_id_2951` text,
  `col_id_2961` text,
  `col_id_2971` text,
  `col_id_2981` text,
  `col_id_2991` text,
  `col_id_3001` text,
  `col_id_3011` text,
  `col_id_3021` text,
  `col_id_3031` text,
  `col_id_3041` text,
  `col_id_3051` text,
  `col_id_3061` text,
  `col_id_3071` text,
  `col_id_3081` text,
  `col_id_3091` text,
  `col_id_3101` text,
  `col_id_3111` text,
  `col_id_3121` text,
  `col_id_3171` text,
  `col_id_3181` text,
  `col_id_3201` text,
  `col_id_3211` text,
  `col_id_3221` text,
  `col_id_3231` text,
  `col_id_3241` text,
  `col_id_3251` text,
  `col_id_3261` text,
  `col_id_3271` text,
  `col_id_3281` text,
  `col_id_3291` text,
  `col_id_3301` text,
  `col_id_3311` text,
  `col_id_3321` text,
  `col_id_3331` text,
  `col_id_3341` text,
  `col_id_3351` text,
  `col_id_3361` text,
  `col_id_3371` text,
  `col_id_3381` text,
  `col_id_3391` text,
  `col_id_3401` text,
  `col_id_3801` text,
  `col_id_3811` text,
  `col_id_3821` text,
  `col_id_3831` text,
  `col_id_3851` text,
  `col_id_3861` text,
  `col_id_3871` text,
  `col_id_3881` text,
  `col_id_3891` text,
  `col_id_3901` text,
  `col_id_3911` text,
  `col_id_3921` text,
  `col_id_3931` text,
  `col_id_3941` text,
  `col_id_3951` text,
  `col_id_3961` text,
  `col_id_3971` text,
  `col_id_3981` text,
  `col_id_3991` text,
  `col_id_4001` text,
  `col_id_4011` text,
  `col_id_4021` text,
  `col_id_4031` text,
  `col_id_4041` text,
  `col_id_4051` text,
  `col_id_4061` text,
  `col_id_4071` text,
  `col_id_4081` text,
  `col_id_4091` text,
  `col_id_4101` text,
  `col_id_4111` text,
  `col_id_4121` text,
  `col_id_4131` text,
  `col_id_4141` text,
  `col_id_4151` text,
  `col_id_4161` text,
  `col_id_4171` text,
  `col_id_4181` text,
  `col_id_4191` text,
  `col_id_4201` text,
  `col_id_4211` text,
  `col_id_4221` text,
  `col_id_4231` text,
  `col_id_4241` text,
  `col_id_4251` text,
  `col_id_4261` text,
  `col_id_4271` text,
  `col_id_4311` text,
  `col_id_4321` text,
  `col_id_4331` text,
  `col_id_4341` text,
  PRIMARY KEY (`row_id`),
  KEY `site_id` (`site_id`),
  KEY `entry_id` (`entry_id`),
  KEY `field_id` (`field_id`),
  KEY `var_id` (`var_id`)
) ENGINE=InnoDB AUTO_INCREMENT=151581 DEFAULT CHARSET=utf8

**Comment by kevincupp** [comment]
Looking at the query from the error, it could be that the bulk of import had already completed before that point. I think that query is the one that updates the searchable data, so I would think that it has otherwise imported all your data and you might be fine ignoring this. If you look in your `exp_grid_columns` table, do you see all your columns in there? And do you see the corresponding data in the `exp_channel_grid_field_x` tables?

**Comment by JonaGreen** [comment]
exp_grid_columns value is 0 with no exp_channel_grid_field_x being created.
There is however 7607 records in the exp_relationships table but this is opposed to 10827 in the exp_playa_relationships.
I noticed that by continually trying the import new grid/relationship entry fields were created up until timeout so I rolled back to prevent a backlog of superfluous fields.

**Comment by JonaGreen** [comment]
Just a query but I noticed Wygwam isn't supported in grid.  I use Wygwam often in matrix cells, could this be causing an issue?

**Comment by kevincupp** [comment]
Interesting. So your last comment suggests new Grid fields are being created, but they do not have corresponding tables and columns? Do they only exist in the channel_fields table?

Wygwam works in Grid, where did you find that it wasn't? If it weren't, I doubt it would cause the problem you're seeing here.

Are you able to send me a copy of your database? I've been suspecting this is largely environmental so I want to test and see if I can run the import on my end using your data. If it ends up being a problem in the add-on, I'll be able to fix it more easily. If that sounds good, send us a copy of your database to team@ellislab.com.

**Comment by JonaGreen** [comment]
The grid fields were an observation of the values in the SQL manager.
Upon setting Grid as a new channel field I tried to add Wygwam as a data type in the first column and it wasn't an option so assumed it wasn't supported.

I have been back and forth with the IT department to arrange a MySQL dump of the database, they're requesting the signing of an NDA prior to sending, will that be OK?

**Comment by kevincupp** [comment]
Sounds like you got this sorted. As for Wygwam, make sure you have the latest version and contact EEHarbor if you still have trouble

**Comment by JonaGreen** [comment]
Many thanks for all your help Kevin!



Cheers

Jon

*Jonathan Green*
*Web Developer*
*BSc (Hons) MMT*

*Pico Technology*
James House, Colmworth Business Park,
St Neots, Cambridgeshire, PE19 8YP.

Email: jonathan.green@picotech.com

Tel:+44 (0) 1480 396 395 <+441480396395>
Fax:+44 (0) 1480 396 296 <+441480396296>

[image: http://www.picotech.com/images/signature.png]
<http://www.picotech.com/>





*From:* Kevin Cupp [mailto:notifications@github.com]
*Sent:* 15 September 2017 05:23
*To:* EllisLab/PlayaMatrixImporter
*Cc:* Jonathan Green; Author
*Subject:* Re: [EllisLab/PlayaMatrixImporter] Timeout errors (#14)



Sounds like you got this sorted. As for Wygwam, make sure you have the
latest version and contact EEHarbor if you still have trouble

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/EllisLab/PlayaMatrixImporter/issues/14#issuecomment-329677698>,
or mute the thread
