### ISSUE TITLE
Duplicated rows

### ISSUE THREAD

**Issue by joyetrit** [EllisLab/PlayaMatrixImporter#15]
We're using Publisher and after we run the Importer, and upgrade from EE2 to EE3, we found that there are duplicated rows in some grid rows. Maybe this is caused by the multiple languages we have? I saw that in your documentation you mentioned

> If you have Publisher and Low Search installed, you'll need to regenerate Collections before editing entries.

Can you clarify that this might be the fix for our issues and what do you mean by regenerate the collections? Thanks!

**Comment by kevincupp** [comment]
Does the content in the duplicate rows correspond to the different languages you have? If so, yes, that must be it. But if you have Publisher installed, I'd imagine it should sort that out for you as its supposed to alter the query to show your preferred language.

As for the collections note, I'm actually not too familiar with Low Search, I think either Low or Brian (Publisher) told me about this so I added it to the docs. The collections thing likely only affects searching, if I understand it correctly.

**Comment by joyetrit** [comment]
Hello there,

The duplicated rows are not exactly the amount of languages we have, but
exactly doubled. What is weird is that both the playa field and the
relationship field have exactly the rows with double amount of our
languages duplicated. I think in this case it seems to be more of a
Publisher problem? or do you know any EE upgrade code that might have
created the duplicates?

Thanks!

**Comment by kevincupp** [comment]
I can't imagine any EE code would have done that. I'd look at Publisher as the core of how it works is duplicating data for entries but then sorting it out later by querying a language column.

**Comment by kevincupp** [comment]
Closing for over a year of inactivity.
