### ISSUE TITLE
A Database Error Occurred

### ISSUE THREAD

**Issue by leeaston** [EllisLab/PlayaMatrixImporter#2]
Tried this, and get this error - my V2 site meets the requirements mentioned in the docs:

A Database Error Occurred
Error Number: 1054

Unknown column 'var_id' in 'where clause'

SELECT * FROM (`exp_matrix_cols`) WHERE `var_id` IS NULL

Filename: third_party/el_playamatrix_importer/libraries/matrix_importer.php

Line Number: 168

**Comment by kevincupp** [comment]
Hi Lee, sorry for the trouble. I've just pushed up 1.0.2 which should fix this. Can you give it a try?
