### ISSUE TITLE
php errors on start

### ISSUE THREAD

**Issue by skookie000** [EllisLab/PlayaMatrixImporter#3]
EE 2.11.3, Matrix 2.6.1, php 5.5, latest importer script (downloaded today).
Only one matrix field, no Playa (did, but converted long time ago, then uninstalled).

In the entries, only two of the 6 fields show up, both text fields.  In total 5 are text fields, one is Assets.

PHP Errors on run:

Severity: Notice
Message: Undefined offset: 114
Filename: libraries/Matrix_importer.php
Line Number: 98

Severity: Warning
Message: Invalid argument supplied for foreach()
Filename: Converters/MatrixConverter.php
Line Number: 73

Severity: Notice
Message: Undefined offset: 114
Filename: libraries/Matrix_importer.php
Line Number: 121

(repeats 17895 times)
Severity: Notice
Message: Undefined offset: 7
Filename: Converters/AssetsCellConverter.php
Line Number: 44

Severity: Warning
Message: Cannot modify header information - headers already sent by (output started at /systempath/system/codeigniter/system/core/Exceptions.php:170)
Filename: core/EE_Input.php
Line Number: 213

Severity: Warning
Message: Cannot modify header information - headers already sent by (output started at /systempath/system/codeigniter/system/core/Exceptions.php:170)
Filename: libraries/Functions.php
Line Number: 446

**Comment by kevincupp** [comment]
Sorry for your trouble! Very strange. Could you open your `exp_matrix_cols` table and tell me if you have any rows that have a `field_id` of `114`? According to the error, it seems you have a Matrix field with no columns.

**Comment by skookie000** [comment]
![screen shot 2016-05-10 at 10 40 02 am](https://cloud.githubusercontent.com/assets/4128963/15152631/96e1b894-169b-11e6-9706-600a144ae64f.png)

**Comment by kevincupp** [comment]
Thanks for that screenshot, that was very helpful. I think it's an issue when you have Low Variables installed as well. I've pushed up version 1.0.3 that I think should clear things up, give it a try and let me know how it goes.

**Comment by skookie000** [comment]
Looks like that update fixed it.  Thanks!!  Hopefully that's it.

**Comment by kevincupp** [comment]
Great to hear! Let us know if you run into anything else.
