### ISSUE TITLE
Undefined offset

### ISSUE THREAD

**Issue by Joobs** [EllisLab/PlayaMatrixImporter#5]
When I run the converter I am getting a white screen with several of the following PHP errors:

```
Severity: Notice
Message: Undefined offset: 50
Filename: Converters/PlayaConverter.php
Line Number: 160

Severity: Notice
Message: Undefined index:
Filename: Converters/PlayaConverter.php
Line Number: 163
```

EE 2.11.2
PHP 5.6.10

The fields do seem to have been converted though.

**Comment by kevincupp** [comment]
Sorry for the trouble, Joobs! I think this can happen if we encounter any Playa data that has been orphaned, meaning the Matrix field/column it belonged to no longer exists. I've put in a check for that so that we'll just skip over that data and this error shouldn't appear. Thanks!
