### ISSUE TITLE
Missing images in Matrix fields

### ISSUE THREAD

**Issue by joshconner** [EllisLab/PlayaMatrixImporter#7]
After the importer ran all of my Matrix fields were converted to Grid but the images within the Grid fields are missing.

I have ExpressionEngine 2.11.4 and Matrix 2.6.1 installed and the Matrix cell is an ExpressionEngine native file type.

**Comment by kevincupp** [comment]
Hi Josh, I'm unable to reproduce this myself. File field data should be a straight 1:1 mapping with no modifications needed. If you look in the database, are the columns actually blank for those rows?

**Comment by joshconner** [comment]
Kevin, Not sure what happened but after a second look it appears that only one of the Matrix fields didn't ported so I just copied the image names from the database and inserted them into the grid table.

Thanks for taking a look!

**Comment by kevincupp** [comment]
Strange. Glad you got it sorted, hopefully it wasn't too much work you had to do, and sorry that something seemed to have went wrong to begin with.
