### ISSUE TITLE
Empty fields on import

### ISSUE THREAD

**Issue by siebird** [EllisLab/PlayaMatrixImporter#8]
Hi,

I'm having issues successfully importing matrix fields over to grid. The script runs and creates the grid fieldtypes and tables, however, all the columns in the grid are `NULL`. Any pointers? 

The matrix is a simple two column field with `file` and `text` fields.

Running: EE 2.11.5, Matrix 2.6.1, Playa 4.5.2

**Comment by kevincupp** [comment]
Hi @siebird, sorry for the trouble. We got a similar issue (#7) in last week but we never got to the bottom of it. To be clear, are ALL generated Grid fields NULL'd out? Or just this one?

**Comment by siebird** [comment]
Hey @kevincupp, no worries–thanks for the response. Here is a [animated gif](http://d.pr/i/4Que) of the database tables. 

Every time I run the import I get the same results as seen above. However, I did notice I'm getting an error visiting an entry: `Fatal error: Call to a member function setSetting() on null in /../third_party/blocks/libraries/EEBlocks/Controller/PublishController.php on line 287`. Would that affect the import?

**Comment by siebird** [comment]
I fixed that error. However I'm still getting `null` data 🤔

**Comment by kevincupp** [comment]
It's hard to say from here. If your install doesn't have sensitive data, could you send us a copy of your database at team@ellislab.com? Maybe redact your members table.

**Comment by siebird** [comment]
Just sent–thanks!

**Comment by kevincupp** [comment]
Thanks so much! Found the cause of the issue and just pushed up a fix that should get you going again: https://github.com/EllisLab/PlayaMatrixImporter/releases/tag/1.0.6

Give it a try and let us know if you have any more trouble.

**Comment by siebird** [comment]
Awesome, it's working!
